### ISSUE TITLE
Add soft quest cap

### ISSUE THREAD

**Issue by ConanODoyle** [ConanODoyle/farming#21]
- Create storage system similar to stack types:
  - Storage type string identifiers
  - Each storage type can either blacklist or whitelist a list of items
  - Each item can blacklist or whitelist a list of storage types
  - Allows for more control over storage, e.g. silos *only* allow crops, toolboxes *only* allow tools, quest items *require* a quest storage, etc.
- Create quest storage brick specifically for quests
- Disable storage of quests in all other storage bricks

This way, players can only hold a quest in each inventory slot, quest storage, and quest deposit boxes (since they can retrieve a copy of that quest at any time).

**Comment by irrelevantirreverent** [comment]
718d154b5f8ceb7b5af1cc64d0018a1ee0cfa418
