### ISSUE TITLE
Lot loading/unloading 

### ISSUE THREAD

**Issue by ConanODoyle** [ConanODoyle/farming#28]
- Unloading lots when server lots are all occupied, based on "oldest lot without their user online"
- Loading lots via some interface/bot interaction to send you to an empty lot you can claim and load your stuff on

**Comment by irrelevantirreverent** [comment]
eca955334bd3a78dea0eec0ac7c4f5457243a879 fixes lot loading, lot auto-unloading still needs testing

**Comment by ConanODoyle** [comment]
Completed with partial testing - needs robust testing in beta play

**Comment by irrelevantirreverent** [comment]
Tested auto-unloading - seems successful
